name = "POD_Fortran"
version = "0.1.0"
license = "MIT"
author = "Songyu"
maintainer = "Songyu"
copyright = "2026 POD Project"
description = "Astrodynamics library using FPM structure"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

link = ["spicelib", "m", "dace_wrapper", "dace_s", "stdc++","openblas"]

[install]
library = false

[[executable]]
name = "run_pod_emdac"
source-dir = "app"
main = "run_pod_emdac.f90"

[[executable]]
name = "run_pod_ut"
source-dir = "app"
main = "run_pod_ut.f90"

[[executable]]
name = "test_gmm_first_step"
source-dir = "app"
main = "test_gmm_first_step.f90"

[[executable]]
name = "run_CRTBP_uprop"
source-dir = "app"
main = "run_CRTBP_uprop.f90"

[[executable]]
name = "run_HFEM_uprop"
source-dir = "app"
main = "run_HFEM_uprop.f90"

[[executable]]
name = "test_ut_first_step"
source-dir = "app"
main = "test_ut_first_step.f90"

[[executable]]
name = "run_radec_convert"
source-dir = "app"
main = "run_radec_convert.f90"

[[test]]
name = "test_sample_particles_from_gmm"
source-dir = "test"
main = "test_sample_particles_from_gmm.f90"

[[test]]
name = "test_stt_crtbp"
source-dir = "test"
main = "test_stt_crtbp.f90"

[[test]]
name = "test_uq_crtbp_comparison"
source-dir = "test"
main = "test_uq_crtbp_comparison.f90"

