name = "AOC_Fortran"
version = "0.1.0"
license = "MIT"
author = "Songyu"
maintainer = "Songyu"
copyright = "2026 CAT Project"
description = "Astrodynamics library using FPM structure"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
# 核心：只声明要链接库的名字
link = ["spicelib", "m"] 

[install]
library = false