name = "POD_Fortran"
version = "0.1.0"
license = "MIT"
author = "Songyu"
maintainer = "Songyu"
copyright = "2026 POD Project"
description = "Astrodynamics library using FPM structure"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

link = ["spicelib", "m", "dace_wrapper", "dace_s", "stdc++","openblas"]

[install]
library = false

[[executable]]
name = "run_pod_emdac"
source-dir = "app"
main = "run_pod_emdac.f90"

[[executable]]
name = "run_pod_ut"
source-dir = "app"
main = "run_pod_ut.f90"

[[executable]]
name = "run_CRTBP_uprop"
source-dir = "app"
main = "run_CRTBP_uprop.f90"

[[executable]]
name = "run_uq_propagation"
source-dir = "app"
main = "run_uq_propagation.f90"


